DROP ALL OBJECTS;
CREATE SCHEMA IF NOT EXISTS testdb;

CREATE TABLE ORGTYPE
(
    ORGTYPE_ID INTEGER NOT NULL,
    ORGTYPE_NAME VARCHAR(100) NOT NULL
);

ALTER TABLE ORGTYPE ADD CONSTRAINT ORGTYPE_PK PRIMARY KEY(ORGTYPE_ID);