spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthcare
    username: root
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false

dataSource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: sa

hibernate:
  format_sql: true
  show_sql: true

server:
  servlet:
    context-path: /healthcare
  port: ${PORT:8080}

