spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthcare
    username: root
    password: password
  liquibase:
    change-log: classpath:db/changelog/changelog.xml

hibernate:
  format_sql: true
  show_sql: true

server:
  servlet:
    context-path: /healthcare
  port: ${PORT:8080}

